title: Shrey Kumar Jain
logo: /assets/img/logo.png
description: Hi, here is my portfolio. I'm learning to build and deploy website based on github pages
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
